# Generated by Django 4.0.4 on 2022-05-21 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_rename_isbn_livro_isbn"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoria",
            name="descricao",
            field=models.CharField(max_length=255),
        ),
    ]
