# Generated by Django 4.0.4 on 2022-05-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_categoria_descricao"),
    ]

    operations = [
        migrations.AddField(
            model_name="livro",
            name="autores",
            field=models.ManyToManyField(
                related_name="livros", to="core.autor"
            ),
        ),
    ]
