# Generated by Django 4.0.4 on 2022-05-21 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_livro_autores"),
    ]

    operations = [
        migrations.RenameField(
            model_name="livro",
            old_name="categoria",
            new_name="categoria_id",
        ),
        migrations.RenameField(
            model_name="livro",
            old_name="editora",
            new_name="editora_id",
        ),
    ]
