# Generated by Django 4.0.4 on 2022-05-27 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Editora", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Livro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("ISBN", models.CharField(max_length=32)),
                ("quantidade", models.IntegerField()),
                ("preco", models.FloatField()),
                (
                    "editora",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="livros",
                        to="Editora.editora",
                    ),
                ),
            ],
        ),
    ]
