# Generated by Django 4.0.4 on 2022-05-27 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Autor", "0001_initial"),
        ("Livro", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="livro",
            name="autores",
            field=models.ManyToManyField(
                related_name="livros", to="Autor.autor"
            ),
        ),
    ]
